language: python
build:
  ci:
    - pip install -r ./requirements/dev.txt
    - pylint *.py
    # Check package and any other shell scripts
    - apt-get install -y shellcheck
    - shellcheck -s bash $(find ./ -name "*.sh")

resources:
  - name: reqExec_repo
    type: gitRepo
    integration: avinci_gh
    pointer:
      sourceName: shippable/reqExec
      branch: master

jobs:
  - name: u16_reqExec_x8664_pack
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: reqExec_runCI
      - IN: reqExec_repo
        switch: off
      - IN: shipit_bits_access_cli
        switch: off
      - TASK:
          name: u16_reqexec_pack
          runtime:
            options:
              env:
                - ARCHITECTURE: "x86_64"
                - OS: "Ubuntu_16.04"
                - ARTIFACTS_BUCKET: "s3://shippable-artifacts/reqExec"
                - REL_VER: "master"
                - BINARY_DIR: "/tmp/reqExec"
              imageName: drydock/u16pytall
              imageTag: v6.2.4
          script:
            - pushd $(shipctl get_resource_state "reqExec_repo")
            - REPO_COMMIT=$(shipctl get_resource_version_key "reqExec_repo" "shaData.commitSha")
            - BINARY_TAR="reqExec-$REL_VER-$ARCHITECTURE-$OS.tar.gz"
            - PACK_SCRIPT="./package/$ARCHITECTURE/$OS/package.sh"
            - S3_BUCKET_BINARY_DIR="$ARTIFACTS_BUCKET/$REL_VER/"
            - $PACK_SCRIPT
            - mkdir -p $BINARY_DIR && cp -r dist $BINARY_DIR
            - tar -zcvf "$BINARY_TAR" -C "$BINARY_DIR" .
            - aws s3 cp --acl public-read "$BINARY_TAR" "$S3_BUCKET_BINARY_DIR"
    on_success:
      script:
        - shipctl put_resource_state_multi $JOB_NAME "versionName=$REPO_COMMIT" "commitSha=$REPO_COMMIT" "S3_BUCKET=$S3_BUCKET_BINARY_DIR" "S3_FILENAME=$BINARY_TAR"

  - name: u14_reqExec_x8664_pack
    type: runSh
    runtime:
      nodePool: x86_u1404_dyn_large_01
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: reqExec_runCI
      - IN: reqExec_repo
        switch: off
      - IN: shipit_bits_access_cli
        switch: off
      - TASK:
          name: u14_reqexec_pack
          runtime:
            options:
              env:
                - ARCHITECTURE: "x86_64"
                - OS: "Ubuntu_14.04"
                - ARTIFACTS_BUCKET: "s3://shippable-artifacts/reqExec"
                - REL_VER: "master"
                - BINARY_DIR: "/tmp/reqExec"
          script:
            - pushd $(shipctl get_resource_state "reqExec_repo")
            - REPO_COMMIT=$(shipctl get_resource_version_key "reqExec_repo" "shaData.commitSha")
            - BINARY_TAR="reqExec-$REL_VER-$ARCHITECTURE-$OS.tar.gz"
            - PACK_SCRIPT="./package/$ARCHITECTURE/$OS/package.sh"
            - S3_BUCKET_BINARY_DIR="$ARTIFACTS_BUCKET/$REL_VER/"
            - $PACK_SCRIPT
            - cp -r dist $BINARY_DIR
            - tar -zcvf "$BINARY_TAR" -C "$BINARY_DIR" .
            - aws s3 cp --acl public-read "$BINARY_TAR" "$S3_BUCKET_BINARY_DIR"
    on_success:
      script:
        - shipctl put_resource_state_multi $JOB_NAME "versionName=$REPO_COMMIT" "commitSha=$REPO_COMMIT" "S3_BUCKET=$S3_BUCKET_BINARY_DIR" "S3_FILENAME=$BINARY_TAR"

  - name: c7_reqExec_x8664_pack
    type: runSh
    runtime:
      nodePool: x86_c07_cus_01
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: reqExec_runCI
      - IN: reqExec_repo
        switch: off
      - IN: shipit_bits_access_cli
        switch: off
      - TASK:
          name: c7_reqexec_pack
          runtime:
            options:
              env:
                - ARCHITECTURE: "x86_64"
                - OS: "CentOS_7"
                - ARTIFACTS_BUCKET: "s3://shippable-artifacts/reqExec"
                - REL_VER: "master"
                - BINARY_DIR: "/tmp/reqExec"
              imageName: drydock/c7pytall
              imageTag: v6.4.4
          script:
            - pushd $(shipctl get_resource_state "reqExec_repo")
            - REPO_COMMIT=$(shipctl get_resource_version_key "reqExec_repo" "shaData.commitSha")
            - BINARY_TAR="reqExec-$REL_VER-$ARCHITECTURE-$OS.tar.gz"
            - PACK_SCRIPT="./package/$ARCHITECTURE/$OS/package.sh"
            - S3_BUCKET_BINARY_DIR="$ARTIFACTS_BUCKET/$REL_VER/"
            - $PACK_SCRIPT
            - cp -r dist $BINARY_DIR
            - tar -zcvf "$BINARY_TAR" -C "$BINARY_DIR" .
            - aws s3 cp --acl public-read "$BINARY_TAR" "$S3_BUCKET_BINARY_DIR"
    on_success:
      script:
        - shipctl put_resource_state_multi $JOB_NAME "versionName=$REPO_COMMIT" "commitSha=$REPO_COMMIT" "S3_BUCKET=$S3_BUCKET_BINARY_DIR" "S3_FILENAME=$BINARY_TAR"

  - name: macOS10_reqExec_x8664_pack
    type: runSh
    runtime:
      nodePool: x86_m10_cus_01
      container: false
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: reqExec_runCI
      - IN: reqExec_repo
        switch: off
      - IN: shipit_bits_access_cli
        switch: off
      - TASK:
          name: macOS10_reqexec_pack
          runtime:
            options:
              env:
                - ARCHITECTURE: "x86_64"
                - OS: "macOS_10.12"
                - ARTIFACTS_BUCKET: "s3://shippable-artifacts/reqExec"
                - REL_VER: "master"
                - BINARY_DIR: "/tmp/reqExec"
          script:
            - pushd $(shipctl get_resource_state "reqExec_repo")
            - REPO_COMMIT=$(shipctl get_resource_version_key "reqExec_repo" "shaData.commitSha")
            - BINARY_TAR="reqExec-$REL_VER-$ARCHITECTURE-$OS.tar.gz"
            - PACK_SCRIPT="./package/$ARCHITECTURE/$OS/package.sh"
            - S3_BUCKET_BINARY_DIR="$ARTIFACTS_BUCKET/$REL_VER/"
            - $PACK_SCRIPT
            - cp -r dist $BINARY_DIR
            - tar -zcvf "$BINARY_TAR" -C "$BINARY_DIR" .
            - aws s3 cp --acl public-read "$BINARY_TAR" "$S3_BUCKET_BINARY_DIR"
    on_success:
      script:
        - shipctl put_resource_state_multi $JOB_NAME "versionName=$REPO_COMMIT" "commitSha=$REPO_COMMIT" "S3_BUCKET=$S3_BUCKET_BINARY_DIR" "S3_FILENAME=$BINARY_TAR"


  - name: u16_reqExec_aarch64_pack
    type: runSh
    runtime:
      nodePool: aarch64_u1604_cus_01
      # pip fails while installing pyinstaller, while running in a container.
      # so, running this job on host
      container: false
    triggerMode: parallel
    dependencyMode: strict
    steps:
      - IN: reqExec_runCI
      - IN: reqExec_repo
        switch: off
      - IN: shipit_bits_access_cli
        switch: off
      - TASK:
          name: install awscli
          script:
            - export LC_ALL=C
            - pip install awscli==1.11.91
      - TASK:
          name: u16aarch64_reqexec_pack
          runtime:
            options:
              env:
                - ARCHITECTURE: "aarch64"
                - OS: "Ubuntu_16.04"
                - ARTIFACTS_BUCKET: "s3://shippable-artifacts/reqExec"
                - REL_VER: "master"
                - BINARY_DIR: "/tmp/reqExec"
          script:
            - pushd $(shipctl get_resource_state "reqExec_repo")
            - REPO_COMMIT=$(shipctl get_resource_version_key "reqExec_repo" "shaData.commitSha")
            - BINARY_TAR="reqExec-$REL_VER-$ARCHITECTURE-$OS.tar.gz"
            - PACK_SCRIPT="./package/$ARCHITECTURE/$OS/package.sh"
            - S3_BUCKET_BINARY_DIR="$ARTIFACTS_BUCKET/$REL_VER/"
            - $PACK_SCRIPT
            - cp -r dist $BINARY_DIR
            - tar -zcvf "$BINARY_TAR" -C "$BINARY_DIR" .
            - aws s3 cp --acl public-read "$BINARY_TAR" "$S3_BUCKET_BINARY_DIR"
    on_success:
      script:
        - shipctl put_resource_state_multi $JOB_NAME "versionName=$REPO_COMMIT" "commitSha=$REPO_COMMIT" "S3_BUCKET=$S3_BUCKET_BINARY_DIR" "S3_FILENAME=$BINARY_TAR"

  - name: w2k16_reqExec_x8664_pack
    type: runSh
    triggerMode: parallel
    dependencyMode: strict
    runtime:
      nodePool: x86_w16_cus_01
      container: false
    steps:
      - IN: reqExec_runCI
      - IN: shipit_bits_access_cli
        switch: off
      - IN: reqExec_repo
      - TASK:
          name: w2k16_reqexec_pack
          runtime:
            options:
              env:
                - ARCHITECTURE: "x86_64"
                - OS: "WindowsServer_2016"
                - ARTIFACTS_BUCKET: "s3://shippable-artifacts/reqExec"
                - REL_VER: "master"
                - BINARY_DIR: "/tmp/reqExec"
          script:
            - $ErrorActionPreference = "Stop"
            - $env:REPO_COMMIT = $(shipctl get_resource_version_key "reqExec_repo" "shaData.commitSha")
            - $env:REQ_EXEC_PATH = $(shipctl get_resource_state "reqExec_repo")
            - $env:REQ_EXEC_PACKAGE_PATH = [System.IO.Path]::Combine($env:REQ_EXEC_PATH, "package", $env:ARCHITECTURE, $env:OS)
            - $env:REQ_EXEC_BINARY_DIR = Join-Path "$env:TEMP" "reqExec"
            - $env:REQ_EXEC_BINARY_ZIP = "reqExec-${env:REL_VER}-${env:ARCHITECTURE}-${env:OS}.zip"
            - $env:S3_BUCKET_BINARY_DIR = "${env:ARTIFACTS_BUCKET}/${env:REL_VER}/"
            - if (Test-Path $env:REQ_EXEC_BINARY_DIR) {Remove-Item -Recurse -Force $env:REQ_EXEC_BINARY_DIR}
            - New-Item -ItemType directory $env:REQ_EXEC_BINARY_DIR
            - pushd $env:REQ_EXEC_PATH
            - >
              & $env:REQ_EXEC_PACKAGE_PATH\package.ps1
            - $env:bin_directory = ".\dist\main" # main.exe should be inside dist/main/ instead of dist/
            - New-Item -ItemType Directory -Force -Path $env:bin_directory
            - Move-Item -Force .\dist\main.exe $env:bin_directory
            - Copy-Item dist -Destination $env:REQ_EXEC_BINARY_DIR -Recurse
            - Compress-Archive -Force -Path "$env:REQ_EXEC_BINARY_DIR\*" -DestinationPath $env:REQ_EXEC_BINARY_ZIP
            - aws s3 cp --acl public-read "$env:REQ_EXEC_BINARY_ZIP" "$env:S3_BUCKET_BINARY_DIR"
    on_success:
      script:
        - shipctl put_resource_state_multi $env:JOB_NAME "versionName=$env:REPO_COMMIT" "commitSha=$env:REPO_COMMIT" "S3_BUCKET=$env:S3_BUCKET_BINARY_DIR" "S3_FILENAME=$env:REQ_EXEC_BINARY_ZIP"
